check_interval_seconds: 600
device_alias: LOCAL
dns_servers:
- 100.64.0.23
enable_nostr: true
isp_ip: 58.182.96.191
log_retention_days: 30
nostr_pubkey: npub1yourkeyhere
send_dm: true
trusted_ips:
- 138.199.60.10
